server:
  port: 8001

spring:
  application:
    name: cart-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  feign:
    productsAPI:
      url: http://localhost:8002/products

  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3306/shoppingcart-service?serverTimezone=UTC
      username: root
      password: ''
    database-platform: org.hibernate.dialect.MySQL8Dialect
